Enhance Docstrings in `aepsych/kernels`
facebookresearch/aepsych pull request #427
Opened 2024-10-31 12:31 UTC by yalsaffar

One of several PRs addressing issue #366 to improve docstring coverage.

Improves documentation in `aepsych/kernels` for better clarity and consistency.
- Adds missing docstrings to functions and methods across kernel modules.
- Updates existing docstrings with refined type hints and a unified structure.

2024-11-11 17:01 UTC, JasonKChow commented
Need rebase, let me know when this is rebased and I'll import it to internal.

2024-11-11 17:02 UTC, JasonKChow requested changes
Need rebase

2024-11-12 17:07 UTC, JasonKChow approved these changes

2024-11-12 17:38 UTC, crasanders requested changes

2024-11-12 17:38 UTC, crasanders commented on aepsych/kernels/pairwisekernel.py
> +          self, latent_kernel: Any, is_partial_obs: bool=False, **kwargs
I guess I missed this before, but the type of latent_kernel should be Kernel

2024-11-12 17:38 UTC, crasanders commented on aepsych/kernels/rbf_partial_grad.py
> +            diag (bool): Should the Kernel compute the whole covariance matrix or just the diagonal? Defaults to False.
```suggestion
            diag (bool): Should the Kernel compute the whole covariance matrix (False) or just the diagonal (True)? Defaults to False.
```

2024-11-15 02:52 UTC, closed without merging